---
title: "Continuous Improvement"
author: "George Self"
date: 2018-09-04T08:00:00-07:00
description: "-- Strategic planning, the Cochise College way! --"
categories: ["cochise"]
tags: ["strategic","planning"]
---

```{r setup, include=FALSE}
# Load some libraries
library(here)

# Set the rproj home directory
here::here()

```

Far too often, strategic planning is a process that requires thousands of hours from scores of staff members to produce a massive document that ends up decorating the president’s bookshelf with very little practical application. Strategic plans in higher education are typically very comprehensive and unworkable, attempting to consolidate strategies for every facet of the college operations. Cochise College undertakes strategic planning from a different perspective. Our senior leadership is determined that it is far better to find just one goal that can move the proverbial needle within about a year, then select another goal for the next year. This process has successfully enabled us to make significant changes in the information technology infrastructure and student success programs.

The process used in previous years, while successful, was also somewhat labor-intensive. We would convene a very large group of stakeholders for four or more meetings throughout the academic year and that group would eventually determine the singular goal that would be worked on over the upcoming year.

This document outlines an improved process for managing the strategic improvement activity, called the Cochise College Institutional Continuous Improvement Program (ICIP). The goal of ICIP is to provide a singular annual strategic goal that leads to improvement in one essential facet of the college’s operations. Each ICIP project is designed to take about 15 months but more than one is expected to be underway at any given time.

## Timeline

Following is the ICIP timeline.

* March: The President’s Council determines the facet of the college’s operation in greatest need of improvement, which becomes the project domain.

* April: The Executive Vice President of Instruction and Provost (EVIP) identifies the ICIP Action Team (ICIPAT) to implement the ICIP plan. The ICIPAT is composed of 8-10 experts in the project domain. As an example, if the domain is “Improving the Prison Education Program” then the ICIPAT could be composed of staff members like the Dean responsible for that program, the Director of the prison education program, the full-time faculty members who teach at the prison, and others with direct knowledge of that program. This team will ultimately be responsible for focusing the domain to a single issue, planning a solution for that issue, implementing that plan, and evaluating the result of that activity.

* May-August: Institutional Research, in concert with other experts, prepares a background report to guide the ICIPAT’s effort. This is anticipated to be a significant report that combines statistical analysis, web research, local interviews or surveys, and other data-producing efforts.

* August: The EVIP designates a staff member to be the lead facilitator for the project.

* August: The facilitator distributes the background report to members of the ICIPAT. The team members are requested to consider the domain and develop an individual “mini-SWOT” analysis which will be returned to the facilitator.

* September: The facilitator convenes an ICIP Steering Group comprised of 15-20 staff members representing a wide sampling of the college community who are stakeholders in the domain. The purpose of the Steering Group is to brainstorm ideas and narrow the scope of the domain to only a few salient issues.

* October: The ICIPAT meets to determine how they will proceed with the project. The group may draw in other resources as needed to filter their work to a single issue. They will also propose the steps they will take to solve the issue in the spring semester.

* November: The ICIP Steering Group meets with the ICIPAT to finalize the plan. They will report to the Provost and arrange for whatever resources (fiscal, personnel, etc.) they will need to implement their plan.

* January: The ICIPAT implements the strategic plan with assistance from the facilitator.

* May: The ICIPAT reports to the Provost concerning the success of the plan. At that time a decision is made concerning ending the project or perhaps continuing it if extra time would be beneficial.

* May: The facilitator will prepare an after-action report to the President’s Council to describe the specific strategic issue addressed and an evaluation of the results of that effort.

## Summary

The Institutional Continuous Improvement Program is designed to enable continuous strategic improvement without generating a tedious "Strategic Plan” that has proven to be somewhat less than useful in earlier years. This is a new program and will, no doubt, require a certain amount of adjustment over the next few years, but it is hoped that it will permit the college to see significant improvement in a narrowly-focused effort every year.



