---
title: "Moving Day!"
author: "George Self"
date: 2018-08-21T08:00:00-07:00
description: "-- The start of something big! --"
categories: ["cochise"]
tags: []
---

# The Start of Something Big!

I was recently transferred from the Cochise College Institutional Research department to Special Assistant to the Provost. In this new role, I have been given a good bit of freedom to explore the college’s data and look for interesting relationships and other facts. I have a number of tools available to me, including _SQL_, _R_, _Tableau_, and _Rapid-Miner_. However, for simplicity, I’ve decided to focus the lion’s share of my time and talent (at least at first) on _R_ and use the various _R_ tools (like _ggplot_, _plotly_, and _shiny_) to explore and analyze data. That will also require me to improve my skills with _SQL_ so I can extract the data that I’m analyzing from the various databases available at Cochise College.

My goal for the first month is to expand my expertise with both _R_ and _SQL_ and look for simple sorts of data nuggets. After about a month, I plan to begin to expand my _R_ repertoire with various machine learning algorithms and other advanced analytics. After that, I plan to start integrating data from sources that the college has never fully exploited, like AZ ASSIST (the Arizona college transfer database), the National Clearinghouse (federal college transfer database), and the Integrated Postsecondary Education System (IPEDS).

I’m looking forward to the challenge that lies ahead and trust that my work will prove valuable to the senior administration at Cochise College.